### ISSUE TITLE
OpenTAP Linux smartinstaller doesn't install on Ubuntu 20.04.2 64-bit

### ISSUE THREAD

**Issue by alan-copeland-keysight** [opentap/opentap#1126]
Tried with 9.20.0 and 9.21.0, same behavior:

```
curl -Lo OpenTAP "https://packages.opentap.io/4.0/Objects/www/OpenTAP?version=9.21.0&os=Linux"
chmod  +x OpenTAP
sudo ./OpenTAP

file -> /tmp/opentap-installer-840402884/SmartInstaller.Config.xml
file -> /tmp/opentap-installer-840402884/installer-cross
file -> /tmp/opentap-installer-840402884/set-permissions.sh
Setting 0775 permissions on installer-cross
dir -> /tmp/opentap-installer-840402884/opentap
dir -> /tmp/opentap-installer-840402884/opentap/X64
file -> /tmp/opentap-installer-840402884/opentap/X64/opentap.TapPackage
Output from Installer (--installer-path /home/acopelan/Downloads/OpenTAP)
---------------------
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x6cf9c2]

runtime stack:
runtime.throw({0x76cac8?, 0x7f0a499e6bc2?})
	/usr/lib/go-1.19/src/runtime/panic.go:1047 +0x5d fp=0x7fff0c924cd0 sp=0x7fff0c924ca0 pc=0x43a7fd
runtime.sigpanic()
	/usr/lib/go-1.19/src/runtime/signal_unix.go:819 +0x369 fp=0x7fff0c924d20 sp=0x7fff0c924cd0 pc=0x450309

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x6cf570, 0xc00013dac0)
	/usr/lib/go-1.19/src/runtime/cgocall.go:158 +0x5c fp=0xc00013da98 sp=0xc00013da60 pc=0x408ddc
github.com/webview/webview._Cfunc_webview_set_title(0x0, 0x25281f0)
	_cgo_gotypes.go:290 +0x45 fp=0xc00013dac0 sp=0xc00013da98 pc=0x6c1345
github.com/webview/webview.(*webview).SetTitle.func2(0x25281f0?, 0x9?)
	/root/go/pkg/mod/github.com/webview/webview@v0.0.0-20220613032649-1df219123fb2/webview.go:180 +0x4c fp=0xc00013db00 sp=0xc00013dac0 pc=0x6c1b8c
github.com/webview/webview.(*webview).SetTitle(0x412907?, {0xc00001aa34?, 0x74a920?})
	/root/go/pkg/mod/github.com/webview/webview@v0.0.0-20220613032649-1df219123fb2/webview.go:180 +0x65 fp=0xc00013db40 sp=0xc00013db00 pc=0x6c1ae5
main.StartInstaller()
	/builds/tap/smartinstaller/Installer-Cross/Installer/main.go:150 +0xb7 fp=0xc00013db98 sp=0xc00013db40 pc=0x6ce7d7
main.main()
	/builds/tap/smartinstaller/Installer-Cross/Installer/main.go:138 +0x1b3a fp=0xc00013df80 sp=0xc00013db98 pc=0x6ce51a
runtime.main()
	/usr/lib/go-1.19/src/runtime/proc.go:250 +0x212 fp=0xc00013dfe0 sp=0xc00013df80 pc=0x43d052
runtime.goexit()
	/usr/lib/go-1.19/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00013dfe8 sp=0xc00013dfe0 pc=0x46a361

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/go-1.19/src/runtime/proc.go:363 +0xd6 fp=0xc000044fb0 sp=0xc000044f90 pc=0x43d416
runtime.goparkunlock(...)
	/usr/lib/go-1.19/src/runtime/proc.go:369
runtime.forcegchelper()
	/usr/lib/go-1.19/src/runtime/proc.go:302 +0xad fp=0xc000044fe0 sp=0xc000044fb0 pc=0x43d2ad
runtime.goexit()
	/usr/lib/go-1.19/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000044fe8 sp=0xc000044fe0 pc=0x46a361
created by runtime.init.6
	/usr/lib/go-1.19/src/runtime/proc.go:290 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/go-1.19/src/runtime/proc.go:363 +0xd6 fp=0xc000045790 sp=0xc000045770 pc=0x43d416
runtime.goparkunlock(...)
	/usr/lib/go-1.19/src/runtime/proc.go:369
runtime.bgsweep(0x0?)
	/usr/lib/go-1.19/src/runtime/mgcsweep.go:278 +0x8e fp=0xc0000457c8 sp=0xc000045790 pc=0x429bce
runtime.gcenable.func1()
	/usr/lib/go-1.19/src/runtime/mgc.go:178 +0x26 fp=0xc0000457e0 sp=0xc0000457c8 pc=0x41ea86
runtime.goexit()
	/usr/lib/go-1.19/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000457e8 sp=0xc0000457e0 pc=0x46a361
created by runtime.gcenable
	/usr/lib/go-1.19/src/runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc00006e000?, 0x854c88?, 0x1?, 0x0?, 0x0?)
	/usr/lib/go-1.19/src/runtime/proc.go:363 +0xd6 fp=0xc000045f70 sp=0xc000045f50 pc=0x43d416
runtime.goparkunlock(...)
	/usr/lib/go-1.19/src/runtime/proc.go:369
runtime.(*scavengerState).park(0xc2f5a0)
	/usr/lib/go-1.19/src/runtime/mgcscavenge.go:389 +0x53 fp=0xc000045fa0 sp=0xc000045f70 pc=0x427c73
runtime.bgscavenge(0x0?)
	/usr/lib/go-1.19/src/runtime/mgcscavenge.go:617 +0x45 fp=0xc000045fc8 sp=0xc000045fa0 pc=0x428245
runtime.gcenable.func2()
	/usr/lib/go-1.19/src/runtime/mgc.go:179 +0x26 fp=0xc000045fe0 sp=0xc000045fc8 pc=0x41ea26
runtime.goexit()
	/usr/lib/go-1.19/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000045fe8 sp=0xc000045fe0 pc=0x46a361
created by runtime.gcenable
	/usr/lib/go-1.19/src/runtime/mgc.go:179 +0xaa

goroutine 5 [finalizer wait]:
runtime.gopark(0xc2fe80?, 0xc000007860?, 0x0?, 0x0?, 0xc000044770?)
	/usr/lib/go-1.19/src/runtime/proc.go:363 +0xd6 fp=0xc000044628 sp=0xc000044608 pc=0x43d416
runtime.goparkunlock(...)
	/usr/lib/go-1.19/src/runtime/proc.go:369
runtime.runfinq()
	/usr/lib/go-1.19/src/runtime/mfinal.go:180 +0x10f fp=0xc0000447e0 sp=0xc000044628 pc=0x41db8f
runtime.goexit()
	/usr/lib/go-1.19/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000447e8 sp=0xc0000447e0 pc=0x46a361
created by runtime.createfing
	/usr/lib/go-1.19/src/runtime/mfinal.go:157 +0x45

goroutine 6 [IO wait]:
runtime.gopark(0x7f0a1867fc00?, 0xc000052c20?, 0x6b?, 0xca?, 0xc000052c40?)
	/usr/lib/go-1.19/src/runtime/proc.go:363 +0xd6 fp=0xc000052bd0 sp=0xc000052bb0 pc=0x43d416
runtime.netpollblock(0x7f0a16d27338?, 0x50?, 0x0?)
	/usr/lib/go-1.19/src/runtime/netpoll.go:526 +0xf7 fp=0xc000052c08 sp=0xc000052bd0 pc=0x435f37
internal/poll.runtime_pollWait(0x7f0a15cf1880, 0x72)
	/usr/lib/go-1.19/src/runtime/netpoll.go:305 +0x89 fp=0xc000052c28 sp=0xc000052c08 pc=0x464f89
internal/poll.(*pollDesc).wait(0xc000096000?, 0x4?, 0x0)
	/usr/lib/go-1.19/src/internal/poll/fd_poll_runtime.go:84 +0x32 fp=0xc000052c50 sp=0xc000052c28 pc=0x4c5092
internal/poll.(*pollDesc).waitRead(...)
	/usr/lib/go-1.19/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0xc000096000)
	/usr/lib/go-1.19/src/internal/poll/fd_unix.go:614 +0x234 fp=0xc000052ce8 sp=0xc000052c50 pc=0x4c68f4
net.(*netFD).accept(0xc000096000)
	/usr/lib/go-1.19/src/net/fd_unix.go:172 +0x35 fp=0xc000052da0 sp=0xc000052ce8 pc=0x597dd5
net.(*TCPListener).accept(0xc0000ae000)
	/usr/lib/go-1.19/src/net/tcpsock_posix.go:142 +0x28 fp=0xc000052dd0 sp=0xc000052da0 pc=0x5a9b08
net.(*TCPListener).Accept(0xc0000ae000)
	/usr/lib/go-1.19/src/net/tcpsock.go:288 +0x3d fp=0xc000052e00 sp=0xc000052dd0 pc=0x5a8e5d
net/http.(*onceCloseListener).Accept(0x859110?)
	<autogenerated>:1 +0x2a fp=0xc000052e18 sp=0xc000052e00 pc=0x6826aa
net/http.(*Server).Serve(0xc00008e000, {0x858ae8, 0xc0000ae000})
	/usr/lib/go-1.19/src/net/http/server.go:3070 +0x385 fp=0xc000052f48 sp=0xc000052e18 pc=0x6608e5
net/http.(*Server).ListenAndServe(0xc00008e000)
	/usr/lib/go-1.19/src/net/http/server.go:2999 +0x7d fp=0xc000052f78 sp=0xc000052f48 pc=0x66051d
net/http.ListenAndServe(...)
	/usr/lib/go-1.19/src/net/http/server.go:3255
main.serve()
	/builds/tap/smartinstaller/Installer-Cross/Installer/WebServer.go:52 +0x45 fp=0xc000052fe0 sp=0xc000052f78 pc=0x6cb265
runtime.goexit()
	/usr/lib/go-1.19/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000052fe8 sp=0xc000052fe0 pc=0x46a361
created by main.StartWebServer
	/builds/tap/smartinstaller/Installer-Cross/Installer/WebServer.go:48 +0x1f1
Could not start /tmp/opentap-installer-840402884/installer-cross - exit status 2
```

.NET Runtime 6.0.16
.NET SDK 6.0.408

.NET not installed with snap (used the Microsoft feed and apt per https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu-2004#add-the-microsoft-package-repository)

**Comment by alnlarsen** [comment]
Hey @alan-copeland-keysight 

I just tried it in Ubuntu 20.04 WSL and that seems to work fine (despite needing to forward the GUI to Windows). 

Can you tell me a bit more about your environment? e.g. the output of `uname --all` and `screenfetch` / `neofetch`?

**Comment by hognala** [comment]
I talked to @StefanHolst about this. I was installing without --quiet, but was installing via ssh, so no UI.

**Comment by alnlarsen** [comment]
@hognala okay, does that mean we can close this?

**Comment by alan-copeland-keysight** [comment]
We captured a new idea to make the SmartInstaller smarter in this area here: https://gitlab.it.keysight.com/tap/smartinstaller/issues/167

You can close this issue.
