### ISSUE TITLE
Problem during installation

### ISSUE THREAD

**Issue by db-ks** [opentap/opentap#1375]
**Describe the bug**
I tried to install a package without specifying the `--version` it failed, I added the `--version` still failed.

**Environment (please complete the following information):**
 - OS: Windows 11
 - OpenTAP Version 9.22.1+9447a2af

**To Reproduce**
Not sure how to reproduce it, but I kept the installation folder for inspection.

**Actual behavior**
```bash
tap package install Runner 1.7.1

Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ComponentModel.Win32Exception: The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at OpenTap.ExecutorSubProcess.Start()
   at OpenTap.Cli.TapEntry.goIsolated()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at tap.Program.Main(String[] args)
^C
```

```
C:\TEMP\RunnerLocal171>tap package install Runner --version 1.7.1

Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ComponentModel.Win32Exception: The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at OpenTap.ExecutorSubProcess.Start()
   at OpenTap.Cli.TapEntry.goIsolated()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at tap.Program.Main(String[] args)
```

**Expected behavior**
The installation happens.

**Additional context**
[SessionLogs.zip](https://github.com/opentap/opentap/files/13869975/SessionLogs.zip)

**Comment by alnlarsen** [comment]
@db-ks have you managed to reproduce this since? 

I was unable to reproduce it, but I get this exact error if I:

1. Install your exact image on a Linux host
2. Copy the installation to a Windows host and manually copy `tap.exe` from a proper windows installation
3. Run tap package install Runner 1.7.1

Is it possible that you used the same installation in WSL and Windows and got in a weird state?

**Comment by db-ks** [comment]
The above scenario happens on my Windows 11, without any WSL.

**Comment by db-ks** [comment]
I kept the environment for you to inspect. I still can reproduce it now:

```
C:\TEMP\RunnerLocal171>tap package install Runner 1.8.0-rc.6

Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ComponentModel.Win32Exception: The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at OpenTap.ExecutorSubProcess.Start()
   at OpenTap.Cli.TapEntry.goIsolated()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at tap.Program.Main(String[] args)
```

**Comment by db-ks** [comment]
Here is the environment: [RunnerLocal171.zip](https://github.com/opentap/opentap/files/14052567/RunnerLocal171.zip)

**Comment by Razvan-Muresan** [comment]
Verified on OpenTAP version 9.23.2
