### ISSUE TITLE
Instantiating HttpPackageRepository with scheme-less URL does not work

### ISSUE THREAD

**Issue by alnlarsen** [opentap/opentap#1407]
Previously, something like `new HttpPackageRepository("packages.opentap.io")` used to work, but now it throws an exception because the scheme was not included.

We should assume `https://` is no scheme is provided.

See exception:

```
13:15:43.868  thread       Exception unhandled in worker thread.
13:15:43.870  thread       UriFormatException: Invalid URI: The format of the URI could not be determined.
13:15:43.872  thread           at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
13:15:43.872  thread           at OpenTap.Package.HttpPackageRepository..ctor(String url)
13:15:43.872  thread           at Keysight.OpenTap.Gui.MainWindow.f.c(String A_0)
13:15:43.872  thread           at Keysight.OpenTap.Gui.MainWindow.g()
13:15:43.872  thread           at OpenTap.TapThread.Process()
13:15:43.872  thread           at OpenTap.ThreadManager.processQueue()
13:15:43.880  thread       Exception caught at:
13:15:43.882  thread           at Void RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
13:15:43.882  thread           at Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
13:15:43.882  thread           at Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
13:15:43.882  thread           at Void ThreadStart()
```

**Comment by bogdan-achim** [comment]
Verified as fixed
