### ISSUE TITLE
ParentAnnotation is Null casuing an Exception

### ISSUE THREAD

**Issue by witoldpiet** [opentap/opentap#1507]
An OpenTAP user found a bug/regression by upgrading from v9.7 to v9.23.

Two test plans:
 - [SampleChild.TapPlan.txt](https://github.com/opentap/opentap/files/15008959/SampleChild.TapPlan.txt)
 - [SweepPlan.TapPlan.txt](https://github.com/opentap/opentap/files/15008960/SweepPlan.TapPlan.txt)

[SweepPlan.TapPlan.txt](https://github.com/opentap/opentap/files/15008960/SweepPlan.TapPlan.txt) can be opened in OpenTAP v9.7.0+c65b0c5a, while it throws an exception in OpenTAP v9.23.2+5a906a86. 

Error:
```
2024-04-17 11:41:21.461497 ; thread         ; Debug       ; NullReferenceException: Object reference not set to an instance of an object.
2024-04-17 11:41:21.463497 ; thread         ; Debug       ;     at OpenTap.ParameterMemberAnnotator.Annotate(AnnotationCollection annotation)
2024-04-17 11:41:21.463497 ; thread         ; Debug       ;     at OpenTap.AnnotationResolver.Iterate(AnnotationCollection annotation)
2024-04-17 11:41:21.463497 ; thread         ; Debug       ;     at OpenTap.AnnotationCollection.Create(Object object, IReflectionData member, IAnnotation[] extraAnnotations)
2024-04-17 11:41:21.463497 ; thread         ; Debug       ;     at OpenTap.Plugins.BasicSteps.BasicStepsAnnotator.SweepParamsAnnotation.Read(Object source)
2024-04-17 11:41:21.463497 ; thread         ; Debug       ;     at OpenTap.AnnotationCollection.Read()
2024-04-17 11:41:21.463497 ; thread         ; Debug       ;     at OpenTap.MembersAnnotation.GetMember(IMemberData member)
2024-04-17 11:41:21.463497 ; thread         ; Debug       ;     at OpenTap.MembersAnnotation.getMembers()
2024-04-17 11:41:21.463497 ; thread         ; Debug       ;     at Keysight.OpenTap.Wpf.PropGrid.<>c__DisplayClass77_0.<CreateElements>g__process|0()
2024-04-17 11:41:21.463497 ; thread         ; Debug       ;     at Keysight.OpenTap.Wpf.PropGrid.<>c__DisplayClass77_0.<CreateElements>b__1()
2024-04-17 11:41:21.463497 ; thread         ; Debug       ;     at OpenTap.TapThread.Process()
2024-04-17 11:41:21.463497 ; thread         ; Debug       ;     at OpenTap.ThreadManager.processQueue()
2024-04-17 11:41:21.464494 ; thread         ; Debug       ; Exception caught at:
2024-04-17 11:41:21.467152 ; thread         ; Debug       ;     at Void RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
2024-04-17 11:41:21.467152 ; thread         ; Debug       ;     at Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
2024-04-17 11:41:21.467152 ; thread         ; Debug       ;     at Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
2024-04-17 11:41:21.467152 ; thread         ; Debug       ;     at Void ThreadStart()
```

Steps to reproduce:
 - Open [SweepPlan.TapPlan.txt](https://github.com/opentap/opentap/files/15008960/SweepPlan.TapPlan.txt) in Editor
 - Click on Sweep Loop step

Could the root cause of this issue be [this line](
https://github.com/opentap/opentap/blob/1ebaf16af3a2af3c6473f0b14fd02b725c4cc387/Engine/ParameterMemberAnnotator.cs#L100)? Should it be changed to:
```cs 
  annotation.ParentAnnotation?.Add(cache);
```

**Comment by bogdan-achim** [comment]
Verified in OpenTAP v9.24.0-rc.1. The error does not appear anymore
