### ISSUE TITLE
Error when using the System.IO.Ports nuget package

### ISSUE THREAD

**Issue by alnlarsen** [opentap/opentap#1750]
Using a simple netstandard project using the `System.IO.Ports` package, and trying to use any SerialPort function in a CLI action gives me the following exception:

```
00:00:00.346 : CLI           : Debug       : Executing CLI action: SerialTest
00:00:00.346 : tap           : Error       : System.IO.Ports is currently only supported on Windows.
00:00:00.346 : tap           : Debug       : PlatformNotSupportedException: System.IO.Ports is currently only supported on Windows.
00:00:00.362 : tap           : Debug       :     at System.IO.Ports.SerialPort..ctor()
00:00:00.362 : tap           : Debug       :     at SerialTest.Execute(CancellationToken cancellationToken) in C:\Users\allarsen\RiderProjects\ConsoleApp2\ConsoleApp2\Program.cs:line 11
00:00:00.362 : tap           : Debug       :     at OpenTap.Cli.ICliActionExtensions.PerformExecute(ICliAction action, String[] parameters)
00:00:00.362 : tap           : Debug       :     at OpenTap.Cli.CliActionExecutor.Execute(String[] args)
00:00:00.362 : tap           : Debug       : Exception caught at:
00:00:00.362 : tap           : Debug       :     at Void Execute()
00:00:00.362 : tap           : Debug       :     at Void wrapGoInProcess()
00:00:00.362 : tap           : Debug       :     at Void goInProcess()
00:00:00.362 : tap           : Debug       :     at System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
```

**System.IO.Ports is currently only supported on Windows.**

This is a pretty strange error to get because I am building and running this project on Windows.

The error happens because System.IO.Ports ships a common stub dll containing only the public interfaces and documentation, which throws `PlatformNotSupportedException` in all implementations. It also ships platform-dependent implementations in the runtimes directory.

# UPDATE

After some investigation, I now have a good understanding of the behavior we are seeing.

The .NET resolver checks the .deps.json file of the entry assembly (e.g. tap.exe) to figure out which runtime variant to load. `tap.deps.json` does not exist when building `MyPlugin.dll`. Instead, there will be a filed called `MyPlugin.deps.json` in the output folder. This is the file we would like the .NET resolver to consult when loading DLLs in a debug build. Renaming `MyPlugin.deps.json` fixes the exception mentioned above.

A few key takeaways from my investigation:

* In .NET Framework, the OpenTAP resolver gets to resolve a DLL before the default resolver. This behavior has changed in .NET, where several other strategies are tried before "falling back" to the AssemblyResolve hook OpenTAP uses. To ensure the OpenTAP resolver runs first, OpenTAP must override the default load context. See: https://learn.microsoft.com/en-us/dotnet/core/dependency-loading/loading-managed#algorithm
* OpenTAP cannot practically use AssemblyLoadContext without targetting .NET 9, which is not planned for a few releases.
* This is mostly a problem in debug builds. In practice, a package author will package the correct dll for the target runtime.
* In debug builds, the workaround is to copy <X>.deps.json to tap.deps.json to help the default resolver
* When packaging files for release, the solution is to explicitly package the required runtime DLLs

**Comment by rmadsen-ks** [comment]
We need to find a "golden" workaround for these kinds of issues.

**Comment by alnlarsen** [comment]
Example of libgit2sharp workaround mentioned above:

```xml
  <ItemGroup>
    <Content Include="$(NugetPackageRoot)/libgit2sharp.nativebinaries/2.0.315-alpha.0.9/runtimes/linux-x64/native/libgit2-b7bad55.so" CopyToOutputDirectory="PreserveNewest" Link="Dependencies/LibGit2Sharp.0.27.0.0/libgit2-b7bad55.so.x64" />
    <Content Include="$(NugetPackageRoot)/libgit2sharp.nativebinaries/2.0.315-alpha.0.9/runtimes/linux-arm/native/libgit2-b7bad55.so" CopyToOutputDirectory="PreserveNewest" Link="Dependencies/LibGit2Sharp.0.27.0.0/libgit2-b7bad55.so.arm" />
    <Content Include="$(NugetPackageRoot)/libgit2sharp.nativebinaries/2.0.315-alpha.0.9/runtimes/linux-arm64/native/libgit2-b7bad55.so" CopyToOutputDirectory="PreserveNewest" Link="Dependencies/LibGit2Sharp.0.27.0.0/libgit2-b7bad55.so.arm64" />
    <Content Include="$(NugetPackageRoot)/libgit2sharp.nativebinaries/2.0.315-alpha.0.9/runtimes/osx-x64/native/libgit2-b7bad55.dylib" CopyToOutputDirectory="PreserveNewest" Link="Dependencies/LibGit2Sharp.0.27.0.0/libgit2-b7bad55.dylib.x64" />
    <Content Include="$(NugetPackageRoot)/libgit2sharp.nativebinaries/2.0.315-alpha.0.9/runtimes/osx-arm64/native/libgit2-b7bad55.dylib" CopyToOutputDirectory="PreserveNewest" Link="Dependencies/LibGit2Sharp.0.27.0.0/libgit2-b7bad55.dylib.arm64" />
    <Content Include="$(NugetPackageRoot)/libgit2sharp.nativebinaries/2.0.315-alpha.0.9/runtimes/win-x64/native/git2-b7bad55.dll" CopyToOutputDirectory="PreserveNewest" Link="Dependencies/LibGit2Sharp.0.27.0.0/git2-b7bad55.dll.x64" />
    <Content Include="$(NugetPackageRoot)/libgit2sharp.nativebinaries/2.0.315-alpha.0.9/runtimes/win-x86/native/git2-b7bad55.dll" CopyToOutputDirectory="PreserveNewest" Link="Dependencies/LibGit2Sharp.0.27.0.0/git2-b7bad55.dll.x86" />
  </ItemGroup>
```

I think we can agree that this is not pretty, and not something we should encourage in plugins.

**Comment by alnlarsen** [comment]
A workaround for this until we find a good fix could be to add this to a .csproj file using System.IO.Ports (or other such packages):

```xml
<Target Name="OverwriteDepsJson" AfterTargets="CopyFilesToOutputDirectory">
  <Copy SourceFiles="$(OutDir)$(RootNameSpace).deps.json" DestinationFiles="$(OutDir)tap.deps.json"/>
</Target>

```

**Comment by alnlarsen** [comment]
Or if using Editor:

```xml
<Target Name="OverwriteDepsJson" AfterTargets="CopyFilesToOutputDirectory">
  <Copy SourceFiles="$(OutDir)$(RootNameSpace).deps.json" DestinationFiles="$(OutDir)Editor.deps.json"/>
</Target>
```

**Comment by alnlarsen** [comment]
An alternative workaround when using KS8400, which ships its own Deps file, is to use the `--depsfile` launch option in the launch configuration:

`dotnet exec --depsfile ./MyPackage.deps.json Editor.dll`

With this option, it is possible to get .NET to load the deps file for the plugin instead of the deps file for Editor.

**Comment by frederikja163** [comment]
A workaround will be documented in https://github.com/opentap/opentap/pull/2042

**Comment by alnlarsen** [comment]
The workaround is documented in #2042 

Closing this
