### ISSUE TITLE
Cannot copy-paste TestPlanReference after adding an Expression mixin

### ISSUE THREAD

**Issue by alnlarsen** [opentap/opentap#1771]
This was reproduced with:

```
Editor                           - 9.26.1
Expressions                      - 1.2.0
OpenTAP                          - 9.26.1
```

1. Create test plan
2. Add delay step
3. Parameterize delay on test plan
4. Save
5. Create new test plan
6. Add test plan reference step -> reference delay plan
7. Load test plan
8. Copy-paste step -> works
9. Assign Expression to Time Delay
10. Copy-paste step -> no longer works
11. Remove expression -> still does not work

See stack trace:

```
2024-10-03 09:23:15.480057 ; Serializer     ; Error       ; XML Line 3: Unable to locate type 'emb:ref@OpenTap.Plugins.BasicSteps.TestPlanReference'. Are you missing a plugin?
2024-10-03 09:23:15.480057 ; Serializer     ; Error       ; XML Line 3: Unable to locate type 'emb:ref@OpenTap.Plugins.BasicSteps.TestPlanReference'. Are you missing a plugin?
2024-10-03 09:23:15.480057 ; Serializer     ; Error       ; XML Line 3: Unable to locate type 'emb:ref@OpenTap.Plugins.BasicSteps.TestPlanReference'. Are you missing a plugin?
2024-10-03 09:23:15.480057 ; Serializer     ; Error       ; XML Line 3: Unable to read Test Step. Cannot create instance of OpenTap.ITestStep and no default value exists.
2024-10-03 09:23:15.480057 ; Serializer     ; Debug       ; Exception: Cannot create instance of OpenTap.ITestStep and no default value exists.
2024-10-03 09:23:15.480057 ; Serializer     ; Debug       ;     at OpenTap.Plugins.ObjectSerializer.TryDeserializeObject(XElement element, ITypeData t, Action`1 setter, Object newobj, Boolean logWarnings) in C:\git\opentap\Engine\SerializerPlugins\ObjectSerializer.cs:line 84
2024-10-03 09:23:15.480057 ; Serializer     ; Debug       ;     at OpenTap.Plugins.ObjectSerializer.Deserialize(XElement element, ITypeData t, Action`1 setter) in C:\git\opentap\Engine\SerializerPlugins\ObjectSerializer.cs:line 573
2024-10-03 09:23:15.481052 ; Serializer     ; Debug       ; Exception caught at:
2024-10-03 09:23:15.481052 ; Serializer     ; Debug       ;     at Void LogMessages() in C:\git\opentap\Engine\TapSerialization.cs:line 103
2024-10-03 09:23:15.481052 ; Serializer     ; Debug       ;     at System.Object Deserialize(System.Xml.Linq.XDocument, OpenTap.ITypeData, Boolean, System.String) in C:\git\opentap\Engine\TapSerialization.cs:line 0
2024-10-03 09:23:15.481052 ; Serializer     ; Debug       ;     at System.Object Deserialize(System.IO.Stream, Boolean, OpenTap.ITypeData, System.String) in C:\git\opentap\Engine\TapSerialization.cs:line 203
2024-10-03 09:23:15.481052 ; Serializer     ; Debug       ;     at System.Object DeserializeFromString(System.String, OpenTap.ITypeData, Boolean, System.String) in C:\git\opentap\Engine\TapSerialization.cs:line 219
2024-10-03 09:23:15.481052 ; Serializer     ; Debug       ;     ...
2024-10-03 09:23:15.481052 ; App            ; Error       ; Caught unhandled GUI error.
2024-10-03 09:23:15.481052 ; App            ; Debug       ; ArgumentNullException: Value cannot be null.Parameter name: item
2024-10-03 09:23:15.481052 ; App            ; Debug       ;     at OpenTap.TestStepList.InsertItem(Int32 index, ITestStep item) in C:\git\opentap\Engine\TestStepList.cs:line 245
2024-10-03 09:23:15.481052 ; App            ; Debug       ;     at p.a[a](IList`1 A_0, IEnumerable`1 A_1)
2024-10-03 09:23:15.481052 ; App            ; Debug       ;     at Keysight.OpenTap.Gui.TestPlanGrid.DoPaste(String text)
2024-10-03 09:23:15.481052 ; App            ; Debug       ;     at Keysight.OpenTap.Gui.TestPlanGrid.a(Object A_0, KeyEventArgs A_1)
2024-10-03 09:23:15.481052 ; App            ; Debug       ;     at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
2024-10-03 09:23:15.481052 ; App            ; Debug       ;     at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
2024-10-03 09:23:15.481052 ; App            ; Debug       ;     at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
2024-10-03 09:23:15.481052 ; App            ; Debug       ;     at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
2024-10-03 09:23:15.481052 ; App            ; Debug       ;     at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
2024-10-03 09:23:15.481052 ; App            ; Debug       ;     at System.Windows.Input.InputManager.ProcessStagingArea()
2024-10-03 09:23:15.481052 ; App            ; Debug       ;     at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
2024-10-03 09:23:15.481052 ; App            ; Debug       ;     at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
2024-10-03 09:23:15.481052 ; App            ; Debug       ;     at System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
2024-10-03 09:23:15.481052 ; App            ; Debug       ;     at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
2024-10-03 09:23:15.481052 ; App            ; Debug       ;     at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
2024-10-03 09:23:15.481052 ; App            ; Debug       ;     at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
2024-10-03 09:23:15.481052 ; App            ; Debug       ;     at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
2024-10-03 09:23:15.481052 ; App            ; Debug       ;     at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2024-10-03 09:23:15.481052 ; App            ; Debug       ; Exception caught at:
2024-10-03 09:23:15.481052 ; App            ; Debug       ;     at Void a(System.Object, System.Windows.Threading.DispatcherUnhandledExceptionEventArgs)
2024-10-03 09:23:15.481052 ; App            ; Debug       ;     at Boolean CatchException(System.Exception)
2024-10-03 09:23:15.481052 ; App            ; Debug       ;     at System.Object TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
2024-10-03 09:23:15.481052 ; App            ; Debug       ;     at System.Object LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
2024-10-03 09:23:15.481052 ; App            ; Debug       ;     ...
```

**Comment by sebastian-pop** [comment]
Fixed
