### ISSUE TITLE
OpenTAP does not support Package Repository v4

### ISSUE THREAD

**Issue by Denrask** [opentap/opentap#484]
```
01:53:20.476 : PackageRepository : Information : The repository 'https://ks8500.alb.is.keysight.com/packages' is not supported.
01:53:20.476 : PackageRepository : Debug       : Exception: The repository 'https://ks8500.alb.is.keysight.com/packages' is not supported.
01:53:20.476 : PackageRepository : Debug       :     at OpenTap.Package.HttpPackageRepository.CheckRepoApiVersion()
01:53:20.476 : PackageRepository : Debug       :     at OpenTap.Package.HttpPackageRepository.downloadPackagesString(String args, String data, String contentType, String accept)
01:53:20.476 : PackageRepository : Debug       :     at OpenTap.Package.HttpPackageRepository.GetPackages(PackageSpecifier package, CancellationToken cancellationToken, IPackageIdentifier[] compatibleWith)
01:53:20.476 : PackageRepository : Debug       :     at OpenTap.Package.PackageRepositoryHelpers.<>c__DisplayClass4_0.<GetPackagesFromAllRepos>b__0(IPackageRepository repo)
01:53:20.476 : PackageRepository : Debug       :     at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
01:53:20.476 : PackageRepository : Debug       :     --- End of stack trace from previous location ---
01:53:20.476 : PackageRepository : Debug       :     at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
01:53:20.476 : PackageRepository : Debug       :     at System.Threading.Tasks.TaskReplicator.Replica.Execute()
01:53:20.476 : PackageRepository : Debug       :   Inner exception: Repository version '4.0.0-beta.24+f17428d9' is not compatible with min required version '^3.0.0'.
01:53:20.477 : PackageRepository : Debug       : Exception caught at:
01:53:20.477 : PackageRepository : Debug       :     at Void ParallelTryForEach[TSource](System.Collections.Generic.IEnumerable`1[TSource], System.Action`1[TSource])
01:53:20.477 : PackageRepository : Debug       :     at System.Collections.Generic.List`1[OpenTap.Package.PackageDef] GetPackagesFromAllRepos(System.Collections.Generic.List`1[OpenTap.Package.IPackageRepository], OpenTap.Package.PackageSpecifier, OpenTap.Package.IPackageIdentifier[])
01:53:20.477 : PackageRepository : Debug       :     at OpenTap.Package.PackageDef GetPackageDefFromRepo(System.Collections.Generic.List`1[OpenTap.Package.IPackageRepository], OpenTap.Package.PackageSpecifier, System.Collections.Generic.List`1[OpenTap.Package.PackageDef])
01:53:20.477 : PackageRepository : Debug       :     at Void ResolveDependency(OpenTap.Package.PackageSpecifier, System.Collections.Generic.List`1[OpenTap.Package.DependencyEdge], System.Collections.Generic.List`1[OpenTap.Package.IPackageRepository], System.Threading.CancellationToken)
01:53:20.477 : PackageRepository : Debug       :     ...
```

https://github.com/opentap/opentap/blob/main/Package/Repositories/HttpPackageRepository.cs#L371

**Comment by Denrask** [comment]
Fixed by PackageRepository
