### ISSUE TITLE
Package Manager default settings not happy on Windows (file:///C:/Program%252520Files/OpenTAP) 

### ISSUE THREAD

**Issue by alan-copeland-keysight** [opentap/opentap#760]
I’m seeing a problem when I install OpenTAP 9.18.4 on Windows where the default Package Manager settings are throwing an error:

00:00:04.273 : Settings : Debug : No settings file exists for PackageManagerSettings. A new instance with default values has been created. [835 us]
00:00:04.285 : UpdateCheck : Warning : Update check against file:///C:/Program%252520Files/OpenTAP failed. See debug messages for details.
00:00:04.287 : UpdateCheck : Debug : DirectoryNotFoundException: File package repository directory not found at: file:///C:/Program%252520Files/OpenTAP
00:00:04.300 : UpdateCheck : Debug : at OpenTap.Package.FilePackageRepository.LoadPath(CancellationToken cancellationToken)
00:00:04.300 : UpdateCheck : Debug : at OpenTap.Package.FilePackageRepository.CheckForUpdates(IPackageIdentifier packages, CancellationToken cancellationToken)
00:00:04.300 : UpdateCheck : Debug : at OpenTap.Package.UpdateCheck.<>c__DisplayClass5_0.b__0(IPackageRepository repo)
00:00:04.304 : UpdateCheck : Debug : Exception caught at:
00:00:04.312 : UpdateCheck : Debug : at Void b__1()
00:00:04.312 : UpdateCheck : Debug : at Void InnerInvokeWithArg(System.Threading.Tasks.Task)
00:00:04.312 : UpdateCheck : Debug : at Void b__0(System.Object)
00:00:04.312 : UpdateCheck : Debug : at Void Execute()
00:00:04.312 : UpdateCheck : Debug : …

image
image
1568×186 51.2 KB
Another effect of this bug is that %TAP_PATH%\Settings\Package Manager.xml is never created.

A third effect is that I can’t install Packages in the Package Manager GUI. I have to install packages from the CLI.

This seems like a bug, maybe in the installer?

![](https://aws1.discourse-cdn.com/business7/uploads/opentap/original/1X/4e366b46d7f0428aff6dd3f8458b84b24a0a1eda.png)

WORKAROUND:

- remove the goofy path via the Package Manager settings UI and save the settings
- reopen OpenTAP
- this seems to resolve all effects mentioned above

**Comment by alan-copeland-keysight** [comment]
@rmadsen-ks
