### ISSUE TITLE
OpenTAP build sometimes produces invalid package XML

### ISSUE THREAD

**Issue by rmadsen-ks** [opentap/opentap#903]
I have seen this multiple times. As far as I know, this only affects building OpenTAP itself. Since I dont know what causes this, it might affect others unbeknown to me.

building OpenTAP and running tap package install gives the following error message:

```
2022-11-02 10:39:25.944315 ; Installation   ; Warning     ; Unable to read package file 'C:\Keysight\Development\opentap\bin\Debug\Packages\OpenTAP\package.xml'. Moving it to '.broken'
2022-11-02 10:39:25.944315 ; Installation   ; Debug       ; XmlException: Data at the root level is invalid. Line 1064, position 11.
2022-11-02 10:39:25.964316 ; Installation   ; Debug       ;     at System.Xml.XmlTextReaderImpl.Throw(Exception e)
2022-11-02 10:39:25.964316 ; Installation   ; Debug       ;     at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
2022-11-02 10:39:25.964316 ; Installation   ; Debug       ;     at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
2022-11-02 10:39:25.964316 ; Installation   ; Debug       ;     at System.Xml.Linq.XElement.Load(XmlReader reader, LoadOptions options)
2022-11-02 10:39:25.964316 ; Installation   ; Debug       ;     at System.Xml.Linq.XElement.Load(Stream stream, LoadOptions options)
2022-11-02 10:39:25.964316 ; Installation   ; Debug       ;     at OpenTap.Package.PackageDef.ConvertXml(Stream stream) in C:\Keysight\Development\opentap\Package\PackageFile.cs:line 499
2022-11-02 10:39:25.964316 ; Installation   ; Debug       ;     at OpenTap.Package.PackageDef.FromXml(Stream stream) in C:\Keysight\Development\opentap\Package\PackageFile.cs:line 491
2022-11-02 10:39:25.964316 ; Installation   ; Debug       ;     at OpenTap.Package.Installation.loadPackageDef(String file) in C:\Keysight\Development\opentap\Package\Installation.cs:line 305
2022-11-02 10:39:25.984366 ; Installation   ; Debug       ; Exception caught at:
2022-11-02 10:39:25.988402 ; Resolver       ; Debug       ; Loaded assembly System.Diagnostics.StackTrace, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a from C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Diagnostics.StackTrace\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Diagnostics.StackTrace.dll
2022-11-02 10:39:25.988402 ; Installation   ; Debug       ;     at OpenTap.Package.PackageDef loadPackageDef(System.String) in C:\Keysight\Development\opentap\Package\Installation.cs:line 305
2022-11-02 10:39:25.988402 ; Installation   ; Debug       ;     at ResultT Invoke(ArgT) in C:\Keysight\Development\opentap\Shared\ReflectionHelper.cs:line 707
2022-11-02 10:39:25.988402 ; Installation   ; Debug       ;     at System.Collections.Generic.Dictionary`2[System.String,OpenTap.Package.PackageDef] GetPackagesLookup() in C:\Keysight\Development\opentap\Package\Installation.cs:line 222
2022-11-02 10:39:25.988402 ; Installation   ; Debug       ;     at OpenTap.Package.PackageDef GetOpenTapPackage() in C:\Keysight\Development\opentap\Package\Installation.cs:line 271
2022-11-02 10:39:25.988402 ; Installation   ; Debug       ;     ...
```

Looking at the package.broken.xml, it ends with this:
```xml
 </Files>
  <PackageActionExtensions>
    <ActionStep ExeFile="Packages/OpenTAP/Tap.Upgrader.exe" ExpectedExitCodes="0" Arguments="" ActionName="install"></ActionStep>
    <ActionStep ExeFile="Packages/OpenTAP/Tap.Upgrader.exe" ExpectedExitCodes="0" Arguments="" ActionName="uninstall"></ActionStep>
  </PackageActionExtensions>
</Package>kage>
```

Notice the extra `kage>` by the end.

It looks like something goes wrong as the XML is written to the disk.

**Comment by alnlarsen** [comment]
@AsgerIversen theorizes this could be because we are opening an existing file without truncating it.
